spec:
  name: haizel-core-api
  services:
    - name: core-api
      environment_slug: node-js
      instance_count: 1
      instance_size_slug: basic-xxs
      source_dir: blp
      build_command: >-
        corepack enable && pnpm install --filter core-api... --frozen-lockfile && pnpm -r --filter 'core-api...' build && pnpm --filter core-api build
      run_command: pnpm --filter core-api exec node dist/main.js
      http_port: 3000
      routes:
        - path: /
      health_check:
        http_path: /health
        initial_delay_seconds: 10
        period_seconds: 10
        timeout_seconds: 5
        failure_threshold: 3
      envs:
        - key: NODE_ENV
          value: production
          type: GENERAL
          scope: RUN_TIME
        - key: PORT
          value: "3000"
          type: GENERAL
          scope: RUN_TIME
        - key: DATABASE_URL
          type: SECRET
          scope: RUN_TIME
        - key: AUTH0_DOMAIN
          type: GENERAL
          scope: RUN_TIME
        - key: AUTH0_CLIENT_ID
          type: SECRET
          scope: RUN_TIME
        - key: AUTH0_CLIENT_SECRET
          type: SECRET
          scope: RUN_TIME
        - key: AUTH0_AUDIENCE
          type: GENERAL
          scope: RUN_TIME
        - key: AUTH0_ISSUER_BASE_URL
          type: GENERAL
          scope: RUN_TIME
        - key: X_TENANT_HEADER
          type: GENERAL
          scope: RUN_TIME
        - key: OPA_URL
          type: GENERAL
          scope: RUN_TIME
        - key: TEMPORAL_ADDRESS
          type: GENERAL
          scope: RUN_TIME
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          type: GENERAL
          scope: RUN_TIME
