spec:
  name: haizel-app
  services:
    - name: core-api
      environment_slug: node-js
      instance_count: 1
      instance_size_slug: basic-xxs
      source_dir: blp
      http_port: 3000
      routes:
        - path: /
      envs:
        - key: DATABASE_URL
          type: SECRET
          scope: RUN_AND_BUILD
        - key: NODE_ENV
          value: production
          type: GENERAL
          scope: RUN_TIME
        - key: PORT
          value: "3000"
          type: GENERAL
          scope: RUN_TIME
      build_command: |
        corepack enable && pnpm install --frozen-lockfile
        pnpm --filter @haizel/db run generate
        pnpm --filter @haizel/api run build
        pnpm --filter core-api run build
      run_command: pnpm --filter core-api run start
