name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - name: Activate Corepack pin
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          pnpm -v

      - name: Install
        run: pnpm install -w --frozen-lockfile

      - name: Build
        run: pnpm -r run build

      - name: Test (unit)
        run: pnpm -r --filter '!connectors' --filter '!./apps/connectors/*' run test --if-present

      - name: Test (connectors)
        run: pnpm -r --workspace-concurrency=1 --filter './apps/connectors/*' run test --if-present
        env:
          PACT_LOG_LEVEL: warn

      - name: Debug pnpm PATH (on failure)
        if: failure()
        run: |
          which pnpm || true
          echo "PATH=$PATH"
          node -v
          pnpm -v
