version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: blp
      POSTGRES_PASSWORD: blp
      POSTGRES_DB: blp
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --memory
      - 1G
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - '9092:9092'
      - '19092:19092'
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  temporal:
    image: temporalio/auto-setup:1.21.0
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
    depends_on:
      - postgres
    ports:
      - '7233:7233'

  temporal-ui:
    image: temporalio/ui:2.20.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - '8080:8080'
    depends_on:
      - temporal

  opa:
    image: openpolicyagent/opa:0.59.0
    command: ['run', '--server', '--addr=0.0.0.0:8181', '/policy/policy-bundle-dev.tar.gz']
    ports:
      - '8181:8181'
    volumes:
      - ./../apps/policy-bundle/dist:/policy

  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    environment:
      MINIO_ROOT_USER: blp
      MINIO_ROOT_PASSWORD: blpsecret
    command: server /data --console-address :9001
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data

  clamav:
    image: clamav/clamav:stable
    ports:
      - '3310:3310'

  connectors-ppe:
    image: node:20
    working_dir: /app
    command: bash -lc "corepack enable && pnpm install && pnpm --filter ppe-adapter dev"
    volumes:
      - ..:/app
    environment:
      - PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis

  connectors-credit:
    image: node:20
    working_dir: /app
    command: bash -lc "corepack enable && pnpm install && pnpm --filter credit dev"
    volumes:
      - ..:/app
    environment:
      - PORT=3002
    ports:
      - '3002:3002'

  connectors-aus:
    image: node:20
    working_dir: /app
    command: bash -lc "corepack enable && pnpm install && pnpm --filter aus-gateway dev"
    volumes:
      - ..:/app
    environment:
      - PORT=3003
    ports:
      - '3003:3003'

  connectors-esign:
    image: node:20
    working_dir: /app
    command: bash -lc "corepack enable && pnpm install && pnpm --filter esign dev"
    volumes:
      - ..:/app
    environment:
      - PORT=3004
    ports:
      - '3004:3004'

  worker:
    image: node:20
    working_dir: /app
    command: bash -lc "corepack enable && pnpm install && pnpm --filter worker dev"
    volumes:
      - ..:/app
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_TASK_QUEUE: blp.default
    depends_on:
      - temporal
      - redis
      - postgres

volumes:
  postgres-data:
  redpanda-data:
  minio-data:
