name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blp
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: pnpm
          cache-dependency-path: blp/pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.0

      - name: Check pnpm version
        run: pnpm --version

      - name: Debug pnpm PATH
        run: |
          which pnpm || true
          echo "PATH=$PATH"
          node -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install -w --frozen-lockfile

      - name: Build
        run: pnpm -r run build

      - name: Test
        run: pnpm -r run test --if-present
