name: lock-guard
on:
  pull_request:
    paths:
      - 'blp/**/package.json'
      - 'blp/pnpm-lock.yaml'
      - 'blp/pnpm-workspace.yaml'
      - '.github/workflows/lock-guard.yml'
jobs:
  verify-lock:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blp
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm (9.12.0)
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false
      - name: Setup Node (20.10.0) with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: pnpm
          cache-dependency-path: blp/pnpm-lock.yaml
      - name: Verify toolchain
        run: |
          node -v
          pnpm -v
      - name: Verify lockfile matches manifests (fast structural check)
        run: pnpm run lock:check
      - name: Verify install with frozen lock (authoritative)
        run: pnpm run lock:verify-ci
